
spring:
  datasource:
    url: jdbc:mysql://162.241.85.93:3306/webflash_batch_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/New_York
    username: webflash_admin
    password: Admin@mysql
    initialization-mode : always
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl : false
  flyway:
   url: jdbc:mysql://162.241.85.93:3306/webflash_batch_management
   user: "webflash_admin"
   password: "Admin@mysql"
   baselineOnMigrate: true    

logging:
  level:
    org.springframework: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate: INFO
    com.tservice.providermanagement.v1: DEBUG
    

session:
  enable:
    url:
      with:
        session:
          id: false    
